# Generated by Django 2.2.5 on 2019-09-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('diplome', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Enseignants',
            },
        ),
    ]
